# Generated by Django 4.0.3 on 2022-03-27 11:16

from django.db import migrations, models
import sellers.models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='company_picture',
            field=models.ImageField(blank=True, null=True, upload_to=sellers.models.upload_profile_picture),
        ),
    ]
