# Generated by Django 4.0.3 on 2022-03-26 16:22

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('validate_day', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_book)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
    ]
